version: "3.8"

services:
  mongodb:
    container_name: mongodb-container
    image: mongo:5
    restart: always
    volumes:
      - db_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: TemplateDb
      MONGO_INITDB_ROOT_USERNAME: mgadmin
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - application-network

  # reverse-proxy:
  #   image: nginx:latest
  #   container_name: nginx-container
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"

  # redis:
  #   container_name: redis-container
  #   image: redis:7.0.0-alpine
  #   ports:
  #     - 6380:6379
  #   networks:
  #     - application-network
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   # command: redis-server --appendonly yes
  #   volumes:
  #     - "./db_data/redis1-volume:/data"

  # postgres:
  #   image: postgres:15
  #   environment:
  #     - POSTGRES_DB=mydb
  #     - POSTGRES_USER=test
  #     - POSTGRES_PASSWORD=test
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

volumes:
  db_data:

networks:
  application-network:
    driver: bridge

